# Generated by Django 3.2.15 on 2022-09-10 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('rate', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('placeId', models.CharField(max_length=70)),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=6)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='QueryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sortBy', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=70)),
                ('auth_to', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.TextField()),
                ('bad', models.TextField()),
                ('neutral', models.TextField()),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tp_nlp_app.place')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchIndex', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tp_nlp_app.place')),
                ('sortType', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tp_nlp_app.querytype')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('likes', models.IntegerField()),
                ('reviewId', models.CharField(max_length=30)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tp_nlp_app.place')),
            ],
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.UniqueConstraint(fields=('placeId',), name='unique_placeId'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('reviewId',), name='unique_reviewId'),
        ),
    ]
