# Generated by Django 3.2.15 on 2022-09-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp_nlp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewId',
            field=models.CharField(max_length=60),
        ),
    ]
